### ISSUE TITLE
use of String.prototype.endsWith not working in node 0.12.10

### ISSUE THREAD

**Issue by kpesanka** [MikaAK/s3-plugin-webpack#24]
Getting "TypeError: undefined is not a function" when trying to use the plugin with node 0.12.10.
```
node_modules/webpack-s3-plugin/dist/s3_plugin.js:170
      return fPath.endsWith(PATH_SEP) ? fPath : fPath + PATH_SEP;

TypeError: undefined is not a function
    at S3Plugin.addSeperatorToPath (node_modules/webpack-s3-plugin/dist/s3_plugin.js:170:20)
```
Apparently endsWith isn't yet available in this version of the v8 engine (3.28.71.19) that node 0.12.10 uses, or so I presume.

To improve backwards compatibility, would it be possible to use lodash's endsWith method in the several places in the s3-plugin-webpack codebase where String.prototype.endsWith (and startsWith) is used? Lodash is already included, so this should be a very minor change. Happy to submit a PR if you're ok with this.

Thanks!

**Comment by MikaAK** [comment]
Yes, this is a perfect solution. I have a bit of maintenance work with this to do on the weekend so I can take care of it. I'm going to move all methods that I can to lodash to improve compatibility.

**Comment by kpesanka** [comment]
Excellent - thank you so much!

**Comment by MikaAK** [comment]
@kpesanka I've changed all the references to lodash in v0.6.6! You should be good to go now!
